/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ListingsService } from "../listings.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ListingsCreateInput } from "./ListingsCreateInput";
import { ListingsWhereInput } from "./ListingsWhereInput";
import { ListingsWhereUniqueInput } from "./ListingsWhereUniqueInput";
import { ListingsFindManyArgs } from "./ListingsFindManyArgs";
import { ListingsUpdateInput } from "./ListingsUpdateInput";
import { Listings } from "./Listings";
import { TripFindManyArgs } from "../../trip/base/TripFindManyArgs";
import { Trip } from "../../trip/base/Trip";
import { TripWhereUniqueInput } from "../../trip/base/TripWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ListingsControllerBase {
  constructor(
    protected readonly service: ListingsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Listings })
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(@common.Body() data: ListingsCreateInput): Promise<Listings> {
    return await this.service.create({
      data: {
        ...data,

        wishlist: data.wishlist
          ? {
              connect: data.wishlist,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        listingCreatedBy: true,
        locationData: true,
        locationType: true,
        mapData: true,
        photos: true,
        placeSpace: true,
        placeType: true,
        price: true,
        title: true,
        updatedAt: true,

        wishlist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Listings] })
  @ApiNestedQuery(ListingsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Listings[]> {
    const args = plainToClass(ListingsFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        listingCreatedBy: true,
        locationData: true,
        locationType: true,
        mapData: true,
        photos: true,
        placeSpace: true,
        placeType: true,
        price: true,
        title: true,
        updatedAt: true,

        wishlist: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Listings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: ListingsWhereUniqueInput
  ): Promise<Listings | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        listingCreatedBy: true,
        locationData: true,
        locationType: true,
        mapData: true,
        photos: true,
        placeSpace: true,
        placeType: true,
        price: true,
        title: true,
        updatedAt: true,

        wishlist: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Listings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: ListingsWhereUniqueInput,
    @common.Body() data: ListingsUpdateInput
  ): Promise<Listings | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          wishlist: data.wishlist
            ? {
                connect: data.wishlist,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          listingCreatedBy: true,
          locationData: true,
          locationType: true,
          mapData: true,
          photos: true,
          placeSpace: true,
          placeType: true,
          price: true,
          title: true,
          updatedAt: true,

          wishlist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Listings })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: ListingsWhereUniqueInput
  ): Promise<Listings | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          listingCreatedBy: true,
          locationData: true,
          locationType: true,
          mapData: true,
          photos: true,
          placeSpace: true,
          placeType: true,
          price: true,
          title: true,
          updatedAt: true,

          wishlist: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/trips")
  @ApiNestedQuery(TripFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Trip",
    action: "read",
    possession: "any",
  })
  async findManyTrips(
    @common.Req() request: Request,
    @common.Param() params: ListingsWhereUniqueInput
  ): Promise<Trip[]> {
    const query = plainToClass(TripFindManyArgs, request.query);
    const results = await this.service.findTrips(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        listings: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/trips")
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "update",
    possession: "any",
  })
  async connectTrips(
    @common.Param() params: ListingsWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/trips")
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "update",
    possession: "any",
  })
  async updateTrips(
    @common.Param() params: ListingsWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/trips")
  @nestAccessControl.UseRoles({
    resource: "Listings",
    action: "update",
    possession: "any",
  })
  async disconnectTrips(
    @common.Param() params: ListingsWhereUniqueInput,
    @common.Body() body: TripWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      trips: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
